const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const screens={}; $$('.screen').forEach(s=>screens[s.id]=s); let current='intro';
let audioCtx=null;
function tone(freq=520,dur=.16,type='sine'){try{audioCtx??=new(window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume();const now=audioCtx.currentTime,o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.setValueAtTime(freq,now);o.frequency.exponentialRampToValueAtTime(freq*1.025,now+dur);g.gain.setValueAtTime(.0001,now);g.gain.exponentialRampToValueAtTime(.045,now+.015);g.gain.exponentialRampToValueAtTime(.0001,now+dur);o.connect(g).connect(audioCtx.destination);o.start(now);o.stop(now+dur+.02)}catch(e){}}
function chord(){tone(392,.32,'sine');setTimeout(()=>tone(523,.32,'sine'),90);setTimeout(()=>tone(659,.42,'sine'),180)}
function show(id){if(!screens[id])return;screens[current]?.classList.remove('active');current=id;screens[id].classList.add('active');if(id==='intro')startIntroGalaxy();if(id==='fall')startWarp();if(id==='galaxy')startGalaxy();if(id==='finale')startBurst();if(id==='ending')startEndingUniverse()}

// A abertura já começa viva assim que o link é carregado.
requestAnimationFrame(()=>startIntroGalaxy());
$$('[data-action]').forEach(b=>b.addEventListener('click',()=>{tone();const a=b.dataset.action;if(a==='enter'){chord();show('fall');setTimeout(()=>show('galaxy'),2900)}else if(a==='story')show('story');else if(a==='nextStory')nextStory();else if(a==='finale')show('finale');else if(a==='ending')show('ending');else if(a==='replay'){si=0;setStory(0);show('intro')}}));

// fundo de estrelas
const bg=document.createElement('canvas');bg.width=innerWidth;bg.height=innerHeight;bg.id='bgStars';$('#space').appendChild(bg);const bc=bg.getContext('2d');let bgStars=[];
function resizeBg(){const d=Math.min(devicePixelRatio||1,1.5);bg.width=innerWidth*d;bg.height=innerHeight*d;bc.setTransform(d,0,0,d,0,0);bgStars=Array.from({length:Math.min(260,Math.floor(innerWidth*innerHeight/4800))},()=>({x:Math.random()*innerWidth,y:Math.random()*innerHeight,r:.2+Math.random()*1.1,a:.15+Math.random()*.7,s:.2+Math.random()*.45}))}resizeBg();addEventListener('resize',resizeBg);
(function bgLoop(t){bc.clearRect(0,0,innerWidth,innerHeight);for(const s of bgStars){s.y+=s.s*.06;if(s.y>innerHeight)s.y=-2;bc.globalAlpha=s.a*(.65+.35*Math.sin(t*.001+s.x));bc.fillStyle='#fff';bc.beginPath();bc.arc(s.x,s.y,s.r,0,Math.PI*2);bc.fill()}requestAnimationFrame(bgLoop)})();

// Pequenos corações luminosos: aparecem como poeira cósmica e atravessam as transições.
const heartField=$('#heartField');
const heartGlyphs=['♡','♥','✦','♡','·'];
const hearts=Array.from({length:innerWidth<700?22:38},(_,i)=>({
 el:(()=>{const e=document.createElement('span');e.className='heart-particle';e.textContent=heartGlyphs[i%heartGlyphs.length];heartField.appendChild(e);return e})(),
 x:Math.random()*100,y:Math.random()*115,dx:(Math.random()-.5)*.018,dy:.006+Math.random()*.014,size:8+Math.random()*17,phase:Math.random()*Math.PI*2,speed:.5+Math.random()*1.3
}));
(function heartLoop(t){const tt=t*.001;for(const h of hearts){h.y-=h.dy*h.speed;h.x+=h.dx; if(h.y<-8){h.y=108+Math.random()*15;h.x=Math.random()*100}const wave=Math.sin(tt*h.speed+h.phase)*.9;h.el.style.left=`${h.x+wave}%`;h.el.style.top=`${h.y}%`;h.el.style.fontSize=`${h.size}px`;h.el.style.opacity=`${.04+.24*(.5+.5*Math.sin(tt*h.speed+h.phase))}`;h.el.style.transform=`translate3d(${wave*5}px,0,0) rotate(${wave*8}deg)`}requestAnimationFrame(heartLoop)})();


let introRAF;
function startIntroGalaxy(){
 const c=$('#introGalaxy');if(!c)return;cancelAnimationFrame(introRAF);const x=c.getContext('2d');const d=Math.min(devicePixelRatio||1,1.5);c.width=innerWidth*d;c.height=innerHeight*d;x.setTransform(d,0,0,d,0,0);const W=innerWidth,H=innerHeight,mobile=W<700,cx=W*.5,cy=H*(mobile?.24:.255),R=Math.min(W,H);
 const stars=Array.from({length:mobile?720:1250},()=>({a:Math.random()*6.28,r:Math.pow(Math.random(),.55)*R*.82,s:.2+Math.random()*1.45,b:.25+Math.random()*.75,p:Math.random()*6.28,z:.2+Math.random()*.8}));
 const dust=Array.from({length:mobile?260:520},()=>({a:Math.random()*6.28,r:R*(.08+Math.random()*.72),s:.35+Math.random()*1.6,p:Math.random()*6.28}));
 const rings=[{rx:.18,ry:.062,rot:-.10,s:.15,gap:.55,a:.55,w:1.2},{rx:.27,ry:.09,rot:.18,s:-.11,gap:.63,a:.44,w:1.0},{rx:.39,ry:.13,rot:-.11,s:.078,gap:.72,a:.34,w:.9},{rx:.53,ry:.176,rot:.12,s:-.048,gap:.57,a:.27,w:.76},{rx:.67,ry:.22,rot:-.05,s:.03,gap:.66,a:.19,w:.62},{rx:.82,ry:.27,rot:.09,s:-.018,gap:.72,a:.12,w:.5}];
 const satellites=Array.from({length:14},(_,i)=>({ring:i%rings.length,phase:i*2.17,s:(i%2?-.075:.055)*(1+i*.02),size:i%5===0?2.4:1.05}));
 const meteors=Array.from({length:7},()=>({x:Math.random()*W,y:Math.random()*H*.58,v:70+Math.random()*150,t:Math.random()*8}));
 function ellipsePoint(rx,ry,rot,a){const ca=Math.cos(a),sa=Math.sin(a),cr=Math.cos(rot),sr=Math.sin(rot);return[cx+ca*rx*cr-sa*ry*sr,cy+ca*rx*sr+sa*ry*cr]}
 function arc(rx,ry,rot,start,end,color,width,dash=0){x.save();x.translate(cx,cy);x.rotate(rot);x.beginPath();if(dash)x.setLineDash([dash,dash*.6]);x.ellipse(0,0,rx,ry,0,start,end);x.strokeStyle=color;x.lineWidth=width;x.stroke();x.restore()}
 function glow(px,py,r,color='rgba(255,255,255,1)'){const g=x.createRadialGradient(px,py,0,px,py,r);g.addColorStop(0,color);g.addColorStop(.15,'rgba(255,190,225,.55)');g.addColorStop(1,'rgba(255,70,170,0)');x.fillStyle=g;x.beginPath();x.arc(px,py,r,0,6.28);x.fill()}
 function loop(ms){if(current!=='intro'){cancelAnimationFrame(introRAF);return}const e=ms*.001;x.clearRect(0,0,W,H);
  const bg=x.createRadialGradient(cx,cy,0,cx,cy,R*.92);bg.addColorStop(0,'rgba(255,74,174,.19)');bg.addColorStop(.13,'rgba(181,68,179,.13)');bg.addColorStop(.32,'rgba(81,69,157,.075)');bg.addColorStop(.62,'rgba(20,13,39,.03)');bg.addColorStop(1,'transparent');x.fillStyle=bg;x.fillRect(0,0,W,H);
  // duas nebulosas cruzadas
  for(let i=0;i<4;i++){x.save();x.translate(cx,cy);x.rotate(-.55+i*.34+Math.sin(e*.025+i)*.018);const ng=x.createLinearGradient(-R,0,R,0);ng.addColorStop(0,'transparent');ng.addColorStop(.30,`rgba(${105+i*25},${65+i*8},${185-i*10},.018)`);ng.addColorStop(.49,`rgba(255,${72+i*13},${170+i*10},${.05-i*.006})`);ng.addColorStop(.60,'rgba(107,73,190,.025)');ng.addColorStop(1,'transparent');x.fillStyle=ng;x.scale(1,.09+i*.028);x.fillRect(-R,-R*.5,R*2,R);x.restore()}
  for(const s of stars){const a=s.a+e*(.002+s.z*.003),px=cx+Math.cos(a)*s.r,py=cy+Math.sin(a)*s.r*.48;const tw=.45+.55*Math.sin(e*(.7+s.b*2)+s.p);x.globalAlpha=s.b*.72*tw;x.fillStyle=s.b>.9?'#fff':'#d9d4ef';x.beginPath();x.arc(px,py,s.s,0,6.28);x.fill();if(s.b>.94&&s.s>1){x.globalAlpha*=.24;x.beginPath();x.arc(px,py,s.s*4.2,0,6.28);x.fill()}}
  x.globalCompositeOperation='lighter';for(const p of dust){const a=p.a+e*(.01+p.s*.002),rr=p.r+Math.sin(e*.6+p.p)*R*.014,px=cx+Math.cos(a)*rr,py=cy+Math.sin(a)*rr*.27;x.globalAlpha=.018+p.s*.018;x.fillStyle=p.s>1.2?'#ff9bcb':'#8e7ee0';x.beginPath();x.arc(px,py,p.s*2.6,0,6.28);x.fill()}x.globalCompositeOperation='source-over';x.globalAlpha=1;
  // grandes estruturas externas
  const outer=.79*R;arc(outer,outer*.255,-.12,e*.015,e*.015+Math.PI*1.38,'rgba(255,201,231,.12)',.75,8);arc(outer*.92,outer*.31,.14,-e*.022+1,-e*.022+4.3,'rgba(137,127,255,.11)',.7,7);arc(outer*1.02,outer*.19,-.24,e*.012+2,e*.012+5.2,'rgba(255,118,192,.075)',.55,5);
  rings.forEach((r,i)=>{const rx=r.rx*R,ry=r.ry*R,rot=r.rot+Math.sin(e*.11+i)*.018,spin=r.s*e+i*.86;arc(rx,ry,rot,0,6.28,`rgba(255,220,237,${r.a*.35})`,r.w*.5);arc(rx,ry,rot,spin+r.gap,spin+6.28-r.gap,`rgba(255,${190-i*8},${225-i*4},${r.a})`,r.w);arc(rx*1.035,ry*1.035,rot,spin-.8,spin-.8+.34,'rgba(255,248,252,.9)',r.w*1.7);arc(rx*.965,ry*.965,rot,spin+2.2,spin+2.2+.24,'rgba(121,222,255,.5)',r.w*1.25);const a=spin+r.gap+.18,[px,py]=ellipsePoint(rx,ry,rot,a);glow(px,py,6+i*1.5);x.fillStyle='#fff';x.globalAlpha=.95;x.beginPath();x.arc(px,py,1.1+i*.16,0,6.28);x.fill()});x.globalAlpha=1;
  satellites.forEach((p,i)=>{const r=rings[p.ring],rx=r.rx*R*1.03,ry=r.ry*R*1.03,rot=r.rot,a=p.phase+e*p.s,[px,py]=ellipsePoint(rx,ry,rot,a);x.globalAlpha=.35+(i%4)*.14;x.fillStyle=i%4===0?'#fff':i%4===1?'#ffd0e5':'#9ddcff';x.beginPath();x.arc(px,py,p.size,0,6.28);x.fill();if(i%4===0){x.globalAlpha=.11;x.beginPath();x.arc(px,py,p.size*5,0,6.28);x.fill()}});x.globalAlpha=1;
  // cruz de energia
  for(let i=0;i<2;i++){const ang=-.45+i*.9+e*.032*(i?1:-1);x.save();x.translate(cx,cy);x.rotate(ang);const lg=x.createLinearGradient(-R*.78,0,R*.78,0);lg.addColorStop(0,'transparent');lg.addColorStop(.47,'transparent');lg.addColorStop(.5,'rgba(255,238,247,.22)');lg.addColorStop(.53,'transparent');lg.addColorStop(1,'transparent');x.strokeStyle=lg;x.lineWidth=.8;x.beginPath();x.moveTo(-R*.78,0);x.lineTo(R*.78,0);x.stroke();x.restore()}
  const pulse=1+Math.sin(e*1.8)*.05,coreR=R*(mobile?.061:.072)*pulse;const halo=x.createRadialGradient(cx,cy,0,cx,cy,coreR*6.5);halo.addColorStop(0,'rgba(255,255,255,.5)');halo.addColorStop(.08,'rgba(255,236,246,.33)');halo.addColorStop(.2,'rgba(255,89,177,.22)');halo.addColorStop(.45,'rgba(111,87,218,.09)');halo.addColorStop(1,'transparent');x.fillStyle=halo;x.beginPath();x.arc(cx,cy,coreR*6.5,0,6.28);x.fill();
  [1.3,1.55,1.86,2.18].forEach((m,i)=>{x.strokeStyle=i%2?'rgba(126,220,255,.18)':'rgba(255,200,228,.23)';x.lineWidth=i===0?1.2:.55;x.beginPath();x.arc(cx,cy,coreR*m,0,6.28);x.stroke()});
  // estrela/núcleo com duas cores
  const core=x.createRadialGradient(cx-coreR*.5,cy-coreR*.55,coreR*.03,cx+coreR*.28,cy+coreR*.35,coreR*1.2);core.addColorStop(0,'#fff');core.addColorStop(.15,'#fff8fc');core.addColorStop(.34,'#ffd7e8');core.addColorStop(.56,'#ff78ba');core.addColorStop(.76,'#a955d4');core.addColorStop(1,'#29112e');x.fillStyle=core;x.beginPath();x.arc(cx,cy,coreR,0,6.28);x.fill();x.strokeStyle='rgba(255,246,251,.72)';x.lineWidth=.9;x.stroke();x.globalAlpha=.38;x.fillStyle='#fff';x.beginPath();x.ellipse(cx-coreR*.32,cy-coreR*.42,coreR*.23,coreR*.1,-.5,0,6.28);x.fill();x.globalAlpha=1;
  const moonA=e*.42+2.8,[mx,my]=ellipsePoint(coreR*1.95,coreR*.35,.12,moonA);x.fillStyle='#d9f5ff';x.beginPath();x.arc(mx,my,1.7,0,6.28);x.fill();glow(mx,my,5,'rgba(117,219,255,1)');
  for(const q of meteors){q.x+=q.v*.016;if(q.x>W+160){q.x=-180;q.y=15+Math.random()*H*.5;q.v=70+Math.random()*150}const len=26+q.v*.18;x.strokeStyle='rgba(255,225,241,.42)';x.lineWidth=.65;x.globalAlpha=.38;x.beginPath();x.moveTo(q.x,q.y);x.lineTo(q.x-len,q.y-len*.12);x.stroke()}x.globalAlpha=1;
  introRAF=requestAnimationFrame(loop)}loop(0)}
let warpRAF;function startWarp(){const c=$('#warp'),x=c.getContext('2d'),d=Math.min(devicePixelRatio||1,1.5);c.width=innerWidth*d;c.height=innerHeight*d;x.setTransform(d,0,0,d,0,0);const W=innerWidth,H=innerHeight,cx=W/2,cy=H/2;const ps=Array.from({length:Math.min(900,Math.floor(W*H/700))},()=>({a:Math.random()*6.28,r:Math.random()*20,z:Math.random(),v:2+Math.random()*7}));const t0=performance.now();function loop(t){if(current!=='fall'){cancelAnimationFrame(warpRAF);return}const e=(t-t0)/1000;x.fillStyle='rgba(1,1,6,.25)';x.fillRect(0,0,W,H);for(const p of ps){p.r+=p.v*(1+e*.9);if(p.r>Math.max(W,H)){p.r=2+Math.random()*20;p.a=Math.random()*6.28;p.v=2+Math.random()*7}const px=cx+Math.cos(p.a)*p.r,py=cy+Math.sin(p.a)*p.r*.72,len=3+p.r*.025;x.globalAlpha=.12+p.z*.75;x.strokeStyle=p.z>.84?'#fff':'#ff9bc9';x.lineWidth=.4+p.z*1.1;x.beginPath();x.moveTo(px-Math.cos(p.a)*len,py-Math.sin(p.a)*len*.72);x.lineTo(px,py);x.stroke()}x.globalAlpha=1;const g=x.createRadialGradient(cx,cy,0,cx,cy,Math.min(W,H)*.3);g.addColorStop(0,'rgba(255,255,255,.12)');g.addColorStop(.1,'rgba(255,102,180,.1)');g.addColorStop(1,'transparent');x.fillStyle=g;x.fillRect(0,0,W,H);warpRAF=requestAnimationFrame(loop)}loop(t0)}

let galaxyRAF;function startGalaxy(){const c=$('#galaxyCanvas'),x=c.getContext('2d'),d=Math.min(devicePixelRatio||1,1.5);c.width=innerWidth*d;c.height=innerHeight*d;x.setTransform(d,0,0,d,0,0);const W=innerWidth,H=innerHeight,cx=W*.67,cy=H*.43,R=Math.min(W,H);const stars=Array.from({length:W<700?2600:4300},()=>({a:Math.random()*6.28,r:Math.pow(Math.random(),.6)*R*.62,s:.2+Math.random()*1.4,q:Math.random()}));let rot=0;function loop(){if(current!=='galaxy'){cancelAnimationFrame(galaxyRAF);return}x.fillStyle='rgba(2,1,7,.25)';x.fillRect(0,0,W,H);const glow=x.createRadialGradient(cx,cy,0,cx,cy,R*.65);glow.addColorStop(0,'rgba(255,105,181,.16)');glow.addColorStop(.25,'rgba(148,63,155,.08)');glow.addColorStop(1,'transparent');x.fillStyle=glow;x.fillRect(0,0,W,H);rot+=.0015;for(const p of stars){const a=p.a+rot*(1.1-p.r/(R*.7));const arm=Math.sin(a*3.2+p.r*.025)*p.r*.085;const px=cx+Math.cos(a)*(p.r+arm),py=cy+Math.sin(a)*(p.r+arm)*.43;x.globalAlpha=.07+p.q*.72;x.fillStyle=p.q>.9?'#fff':'#efb5dc';x.beginPath();x.arc(px,py,p.s,0,6.28);x.fill()}x.save();x.translate(cx,cy);x.rotate(-.08);for(let i=0;i<700;i++){const a=i*.37+rot*2,r=(i/700)*R*.38;const X=16*Math.pow(Math.sin(a),3),Y=13*Math.cos(a)-5*Math.cos(2*a)-2*Math.cos(3*a)-Math.cos(4*a);const px=X*5.5+(Math.random()-.5)*r*.025,py=-Y*5.5+(Math.random()-.5)*r*.025;x.globalAlpha=.12+.3*Math.random();x.fillStyle=i%7===0?'#fff':'#ff78b8';x.beginPath();x.arc(px,py,.5+Math.random()*1,0,6.28);x.fill()}x.restore();x.globalAlpha=1;galaxyRAF=requestAnimationFrame(loop)}loop()}

const stories=[
 ['✦','CAPÍTULO 02 · 01','O jeito de chegar','Tem gente que chega sem fazer esforço e, mesmo assim, deixa uma impressão diferente. Você tem um pouco disso.','fotos/foto1.jpg'],
 ['☾','CAPÍTULO 02 · 02','Alguns detalhes','Tem coisas que a gente percebe sem procurar: o sorriso, o olhar, o jeito de falar. São detalhes que fazem diferença.','fotos/foto2.jpg'],
 ['✧','CAPÍTULO 02 · 03','A beleza nos detalhes','Uma foto mostra um momento. Mas o que chama atenção mesmo é tudo aquilo que aparece sem precisar ser explicado.','fotos/foto3.jpg'],
 ['∞','CAPÍTULO 02 · 04','Uma luz diferente','Você tem um jeito de deixar o ambiente mais bonito. Talvez seja a energia, talvez seja simplesmente você sendo você.','fotos/foto4.jpg'],
 ['✦','CAPÍTULO 02 · 05','Ainda tem muito por descobrir','Cinco fotos passam rápido. E talvez essa seja a melhor parte: ainda existem muitos detalhes seus que eu nem conheço.','fotos/foto5.jpg']
];let si=0;
function setStory(i){const [ic,ch,ti,tx,img]=stories[i];$('#storyIcon').textContent=ic;$('#storyChapter').textContent=ch;$('#storyTitle').textContent=ti;$('#storyText').textContent=tx;$('#storyPhoto').src=img;$('#storyCount').textContent=`${i+1} / 5`;$('.story-progress i').style.width=`${(i+1)*20}%`}
function nextStory(){if(si>=stories.length-1){tone(880,.25,'triangle');setTimeout(()=>show('constellation'),240);return}si++;const card=$('#storyCard');card.style.opacity='0';card.style.transform='translateY(12px) scale(.985)';setTimeout(()=>{setStory(si);card.style.opacity='1';card.style.transform='none'},220);tone(620+si*80,.16)}setStory(0);

let burstRAF;function startBurst(){const c=$('#burstCanvas'),x=c.getContext('2d'),d=Math.min(devicePixelRatio||1,1.5);c.width=innerWidth*d;c.height=innerHeight*d;x.setTransform(d,0,0,d,0,0);const W=innerWidth,H=innerHeight,cx=W/2,cy=H*.48;const ps=Array.from({length:W<700?700:1100},()=>({a:Math.random()*6.28,r:Math.random()*18,v:1.5+Math.random()*6,max:Math.max(W,H)*(.45+Math.random()),s:.3+Math.random()*1.6,b:Math.random()}));function loop(t){if(current!=='finale'){cancelAnimationFrame(burstRAF);return}x.fillStyle='rgba(2,1,7,.12)';x.fillRect(0,0,W,H);for(const p of ps){p.r+=p.v;if(p.r>p.max){p.r=2+Math.random()*20;p.a=Math.random()*6.28}const px=cx+Math.cos(p.a)*p.r,py=cy+Math.sin(p.a)*p.r*.72;x.globalAlpha=.15+p.b*.7;x.fillStyle=p.b>.85?'#fff':'#ff84bd';x.beginPath();x.arc(px,py,p.s,0,6.28);x.fill()}x.globalAlpha=1;burstRAF=requestAnimationFrame(loop)}loop(0)}

let endingRAF;function startEndingUniverse(){const c=$('#endingCanvas'),x=c.getContext('2d'),d=Math.min(devicePixelRatio||1,1.5);c.width=innerWidth*d;c.height=innerHeight*d;x.setTransform(d,0,0,d,0,0);const W=innerWidth,H=innerHeight,cx=W/2,cy=H*.49;const mobile=W<700,count=mobile?520:900;const ps=Array.from({length:count},()=>({a:Math.random()*6.28,r:Math.random()*20,v:.5+Math.random()*(mobile?3.7:5),max:Math.max(W,H)*(.4+Math.random()*1.05),s:.3+Math.random()*(mobile?1.3:1.7),q:Math.random(),ph:Math.random()*6.28}));function loop(t){if(current!=='ending'){cancelAnimationFrame(endingRAF);return}const e=t*.001;x.fillStyle='rgba(2,1,7,.18)';x.fillRect(0,0,W,H);const g=x.createRadialGradient(cx,cy,0,cx,cy,Math.min(W,H)*.58);g.addColorStop(0,'rgba(255,125,190,.09)');g.addColorStop(.18,'rgba(200,65,150,.035)');g.addColorStop(1,'transparent');x.fillStyle=g;x.fillRect(0,0,W,H);for(const p of ps){p.r+=p.v;if(p.r>p.max){p.r=3+Math.random()*20;p.a=Math.random()*6.28}const a=p.a+Math.sin(e*.7+p.ph)*.04,px=cx+Math.cos(a)*p.r,py=cy+Math.sin(a)*p.r*.72,tw=.35+.65*(.5+.5*Math.sin(e*2+p.ph));x.globalAlpha=(.1+p.q*.6)*tw;x.fillStyle=p.q>.88?'#fff':'#ff78b8';x.beginPath();x.arc(px,py,p.s,0,6.28);x.fill();if(p.q>.82){x.globalAlpha*=.3;x.beginPath();x.arc(px,py,p.s*3.5,0,6.28);x.fill()}}x.globalAlpha=1;endingRAF=requestAnimationFrame(loop)}loop(0)}
